version: "3.8"

services:
  db:
    image: postgres:15
    container_name: jet_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: jet_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672" # Interface web do RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  backend:
    build: .
    container_name: jet_backend
    restart: always
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgres://user:password@db:5432/messages_db
      RABBITMQ_URL: amqp://user:password@rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "start"]

volumes:
  postgres_data:
  rabbitmq_data:
